// Merged from two research rounds: the original fintech-site survey (Mercury,
// Ramp, Stripe, Bluevine, Fundbox, Brex, Wealthfront, Chase) and the
// multi-agent typography/icon/detail sweep. Each is a build commitment.
window.HCC_TECHNIQUES = [
  ["Hero proof triad (Fundbox)",
   "Three icon bullets right under the hero subcopy: “$5K–$25M in funding · Options in as fast as 24 hours · A dedicated human advisor.” The numbers land before anyone scrolls."],
  ["Soft-pull microcopy (Bluevine)",
   "“See your options — won’t impact your credit score¹” directly beneath the primary CTA, with an elegant superscript-footnote system like Wealthfront’s."],
  ["Count-up stat row (Stripe · Lendio)",
   "“$XM funded / Y businesses / Z-day close” ticks up on scroll — tabular Inter figures, ~1.5s ease-out, fires once."],
  ["Hairline-border card system (Ramp)",
   "Cream canvas, flat cards with 1px green-tinted borders, 12–16px radii, zero drop shadows. The single biggest “reads as $10k custom” move."],
  ["Single-accent discipline (Stripe · Ramp)",
   "Racing Green appears ONLY on CTAs, links, and active states — every green pixel means “money moves here.”"],
  ["Needs-router in the hero (Chase)",
   "“I need funding for… [equipment / expansion / cash flow / real estate] → See my options.” Qualifies the lead and shows all four products in one widget."],
  ["Numbered steps, oversized numerals (Fundbox · OnDeck)",
   "“01 Apply → 02 Decision → 03 Funded” — big sage Poppins numerals, one line of copy each. The advisor step is what separates us from an algorithm."],
  ["Instant-quote calculator (Lendio · Amex Blueprint)",
   "Three inputs (monthly revenue, time in business, amount) → live estimated range in big tabular numerals — embedded mid-page and at its own URL. The #1 lead-capture pattern found."],
  ["Hover-lift product cards (Stripe · Mercury)",
   "Cards lift 4px with shadow, the chevron nudges 2px right — and our chevron is the logo. Free brand callback on every hover."],
  ["Comparison table, highlighted column (Bankrate pattern)",
   "Term Loan vs SBA vs HELOC vs LOC with rate/term/speed rows, “best for” tags in green, swipeable cards on mobile."],
  ["Progress stepper on the form (Wise · Stripe)",
   "Numbered circles joined by a line, completed steps get Racing Green checkmarks, “Step 2 of 4” label — proven bounce-reducer."],
  ["Outcome-specific testimonials (Fundbox · Chase)",
   "Name + business + city + outcome: “Funded $250K SBA in 9 days — Miami, FL.” Specific outcomes beat logo walls; add a candor disclosure line."],
  ["Trust badges, max three (Wise · Fundbox)",
   "Rating + $ funded + BBB beside the CTA, 32–48px monochrome marks. Three max — more reads like a pawn-shop window."],
  ["Plain-talk broker disclosure (Mercury)",
   "“High Card Capital is a brokerage, not a direct lender. We arrange financing through our network of lending partners.” Honesty formatted as premium copy."],
  ["Skeleton shimmer loading (Wise · Coinbase)",
   "Cream-toned pulsing placeholders while quote results load — never a blank screen. Cheap CSS, outsized perceived quality."],
  ["FAQ of real objections (Wealthfront)",
   "“Do you pull my credit? What does a broker cost me? How fast is SBA really?” — accordion, last section before the final CTA."]
];
